version: '2'
services:
  db:
    image: postgres
    container_name: db_rubysocial
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 

  app:
    build: .
    image: rubysocial
    container_name: app_rubysocial
    ports:
      - "3000:3000"
    depends_on:
      - db
