name: Push Image Docker Hub

on:
  push:
    branches:
      - "**"

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
     
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
     
      - name: GET RELEASE VERSION 
        run: echo "RELEASE_VERSION=$(echo $GITHUB_REF | cut -d / -f 3 | sed 's/v//')" >> $GITHUB_ENV  

      - name: Build and push in Docker hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/rubysocial:${{env.RELEASE_VERSION}}
          build_args: 
            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY_PROD }}
     
      - name: Image digest 
        run: echo ${{ steps.docker_build.outputs.digest }}             
          
