name: Project web-application rubysocial

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - "test*"  

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_docker_image:
    runs-on: ubuntu-latest


    steps:
      - name: SET GITHUB_REF
        run: echo $GITHUB_REF

      - name: SET GITHUB_REF_NAME_ECHO
        run: echo $GITHUB_REF_NAME

      - name: SET RUNNER OS
        run: echo $RUNNER_OS

      - name: TEST ENV
        run: echo ${{ env.REGISTRY }} and ${{ env.IMAGE_NAME }}


      - name: SET GITHUB_REF_TYPE
        run: echo $GITHUB_REF_TYPE 


      - name: echo VERSION
        run: echo $VERSION

      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Test
        run: echo $GITHUB_SHA_SHORT
      
      - name: Get the version 
        id: get_version 
        run: echo "TAG_VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

      - name: Echo TAG_VERSION
        run: echo $TAG_VERSION
