name: Project web-application rubysocial

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - "test*"  

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_docker_image:
    runs-on: ubuntu-latest


    steps:
      - name: SET GITHUB_REF
        # run: echo ::set-env name=RELEASE_VERSION_REF::$(echo ${GITHUB_REF})
        run: echo $GITHUB_REF

      - name: SET GITHUB_REF_NAME_ECHO
        run: echo $GITHUB_REF_NAME

      - name: SET RUNNER OS
        run: echo $RUNNER_OS

      - name: TEST ENV
        run: echo ${{ env.REGISTRY }} and ${{ env.IMAGE_NAME }}


      - name: SET GITHUB_REF_NAME
        # run: echo $env:GITHUB_REF_NAME
        run: echo '::set-output name=VERSION::$(echo $GITHUB_REF)'

      - name: echo VERSION
        run: echo $VERSION
