name: Project web-application rubysocial

on:
  push:
    branches:
      - main

jobs:
  build_docker_image:
    runs-on: ubuntu-18.04
    
    steps:

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
     
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push in Docker hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/rubysocial:${{ steps.get_version.outputs.VERSION }}    

    
