name: Project web-application rubysocial

on:
  push:
    tags:
      - "v1.*"

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    
    steps:

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_LOGIN }}
      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
     
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
     
      - name: GET RELEASE VERSION 
        run: echo "RELEASE_VERSION=$(echo $GITHUB_REF | cut -d / -f 3 | sed 's/v//')" >> $GITHUB_ENV  

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push in Docker hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/rubysocial:${{env.RELEASE_VERSION}}
